debug: true
logging:
  level:
    cn.djjboom.dynamic_datasource.datasource: debug
spring:
  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://192.168.0.150:3306/master?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
      username: root
      password: 123456
    slave:
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://192.168.0.150:3306/slave?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
      username: root
      password: 123456
mybatis:
#  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    use-column-label: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
